// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQtU3T_GsZwlrvE91xsmuYAV3zrhuPT10',
    appId: '1:676511142886:web:bc99194a3cd2c23718bc27',
    messagingSenderId: '676511142886',
    projectId: 'event-app-f9c74',
    authDomain: 'event-app-f9c74.firebaseapp.com',
    storageBucket: 'event-app-f9c74.firebasestorage.app',
    measurementId: 'G-VHX4ZH9XX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbiCLU8O31nnmR02CQyrpEijBHbLFVBr0',
    appId: '1:676511142886:android:20690ecc946f498718bc27',
    messagingSenderId: '676511142886',
    projectId: 'event-app-f9c74',
    storageBucket: 'event-app-f9c74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApEzx5EpLRaaSerf8YO4XD82MEhVhnafY',
    appId: '1:676511142886:ios:f55d70fae26048fa18bc27',
    messagingSenderId: '676511142886',
    projectId: 'event-app-f9c74',
    storageBucket: 'event-app-f9c74.firebasestorage.app',
    iosBundleId: 'com.example.eventPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApEzx5EpLRaaSerf8YO4XD82MEhVhnafY',
    appId: '1:676511142886:ios:f55d70fae26048fa18bc27',
    messagingSenderId: '676511142886',
    projectId: 'event-app-f9c74',
    storageBucket: 'event-app-f9c74.firebasestorage.app',
    iosBundleId: 'com.example.eventPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQtU3T_GsZwlrvE91xsmuYAV3zrhuPT10',
    appId: '1:676511142886:web:26f46db38717694e18bc27',
    messagingSenderId: '676511142886',
    projectId: 'event-app-f9c74',
    authDomain: 'event-app-f9c74.firebaseapp.com',
    storageBucket: 'event-app-f9c74.firebasestorage.app',
    measurementId: 'G-DBV5Y8266Z',
  );
}
